name: deploy_bts
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - scikit-learn>=0.20
  - numpy
  - plotly
  - seaborn
  - imbalanced-learn
  - matplotlib
  - pip
  - notebook
  - spacy
  - pip:
      - streamlit
